---
- name: Up bootstrap VM
  hosts: vm_host
  vars:
    hook_action: install
  tasks:
    - set_fact:
        resources: "{{ resources|default([])|union([item.name]) }}"
      with_items:
        - "{{ hosts }}"
    - set_fact:
        vbmc_host_provided: localhost
      when: vbmc_host_provided is not defined
    - include_role:
        name: redhatci.ocp.ocp_on_libvirt
      vars:
        ansible_python_interpreter: "{{ (ansible_virtualization_type == 'container') | ansible.builtin.ternary(discovered_interpreter_python, '/usr/libexec/platform-python') }}"
